fixed bug in the controller and service files
6amigos-concordia/6amigos-soen341projectF2023 pull request #50
Opened 2023-10-30 17:43 UTC by KaotharReda

2023-10-30 23:01 UTC, huy2272 requested changes

2023-10-30 23:01 UTC, huy2272 commented on server/real_estate/src/main/java/com/realestate/real_estate/repos/Appointment.java
>  @Data
This @Data tag automatically adds getters and setters for you. Is there a reason why you need @Getter and @Setter?

2023-10-30 23:01 UTC, huy2272 commented on server/real_estate/src/main/java/com/realestate/real_estate/controllers/AppointmentsController.java
> +//    @POSTMapping(path = "/appointments/cancel")
Don't commit commented out code

2023-11-02 16:14 UTC, KaotharReda commented
change requested done

2023-11-03 00:12 UTC, huy2272 approved these changes

2023-11-03 02:54 UTC, merged